### ISSUE TITLE
Statistics should list affected apps

### ISSUE THREAD

**Issue by Madis0** [MartinStyk/AndroidApkAnalyzer#12]
For example, I have 7 "prefer external" apps and I would like to know, which apps are they. An intuitive way would be to tap on the graph column to open a popup showing the apps' names and icons.

**Comment by MartinStyk** [comment]
Hi thank you for opening the issue. I have this feature on my todo list.  I will work on it during next weeks. Once implemented, I will let you know

**Comment by MartinStyk** [comment]
Hey, I played around this today. It is implemented and I will release it (probably) during the next week.

**Comment by Madis0** [comment]
Works, but the tap target is quite small on small numbers. Could you make the number label a tap target too?

**Comment by MartinStyk** [comment]
Not sure if used chart library supports this... I will check it.

**Comment by MartinStyk** [comment]
Small tap target should be already fixed by now. Thanks
