### ISSUE TITLE
[Feature Request] Provide copying to clipboard

### ISSUE THREAD

**Issue by rmenessec** [MartinStyk/AndroidApkAnalyzer#20]
It would be very useful if it were possible to copy the extracted text fields to the clipboard.

**Comment by MartinStyk** [comment]
Hi @rmenessec, thank you for opening the issue. What do you think about copying attribute value to the clipboard on long field click? This seems as a good solution to me.

**Comment by rmenessec** [comment]
That seems reasonable. Could you also provide a way to copy fields in bulk? If it would be a lot of work to select individual entries, I'd settle for being able to copy an entire "page" at a time--preferably with both keys and values, so it's clear which data is which.

**Comment by MartinStyk** [comment]
I think it is reasonable to export whole data about app to json. I can add it as an option. It is related to #22.  Is export to json ok or is it better to copy all data to clipboard?

**Comment by rmenessec** [comment]
I'd like to have both, if possible. I'd like to be able to--for example--copy both "Version name" and "Version code" without needing to export all of an APK's attributes. But I'd like to be able to copy both at once, if possible.
