### ISSUE TITLE
[Feature Request]AMOLED Black Mode

### ISSUE THREAD

**Issue by G2159687** [MartinStyk/AndroidApkAnalyzer#26]
Hello!

I'd like to have an AMOLED black mode for easier reading and screen protection.

Thanks!

**Comment by MartinStyk** [comment]
Hi, thank you for opening the issue. I have it on my radar and once I get to implementation, I will let you know

**Comment by G2159687** [comment]
Thanks :)

**Comment by MartinStyk** [comment]
This feature was released on start of 2019. Thank you for your contribution
