### ISSUE TITLE
analyzing not installed apk from SD card not working 

### ISSUE THREAD

**Issue by papppyo** [MartinStyk/AndroidApkAnalyzer#27]
#### Expected behavior

The app provides detailed report not only about installed app but also not
installed Apk so I expected the not installed apk to load up using the ( analyze apk from external file ) option..

#### Actual behavior

On trying to load apk files on SD card, the operation failed 

#### How to reproduce

*Download 

*install

*launch

*click the three vertical dots and then click "analyze apk from external file"

*Finally navigate to folder where you have apk files in your external card and then see what happens....

* Apk analyzer version 2.3.1
* Operating system: Android 7.0 nougat
*Device: Tecno k7 

#### Recording Of The Bug
https://youtu.be/e-eYHe3YGUg

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@pappy/analyzing-not-installed-apk-from-sd-card-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by MartinStyk** [comment]
Hi, 
thank you for opening issue.
 
* The whole issue is about correct conversion of content URL to file path. Seems like it does't work on all android versions. 
* As a (temporary) workaround, you can move our file to internal storage
* I will try to fix it as soon as I get to it :-)

**Comment by papppyo** [comment]
You welcome, Okay....☺

**Comment by BrooklynTX** [comment]
This is still happening and going on repeatedly. I downloaded the app today

**Comment by MartinStyk** [comment]
This should be fixed in 2.4.0 release.
