### ISSUE TITLE
Selected Category Changed On Rotating The Screen

### ISSUE THREAD

**Issue by neupanedipen** [MartinStyk/AndroidApkAnalyzer#28]
#### Expected behavior
The selected option should retain on changing the screen orientation of the app and should show the apps of the selected category on both the screen orientations.

#### Actual behavior
But on changing the orientation of the screen the selected category is changed to &quot;all apps&quot; no matter what you select in another mode.<br>

#### How to reproduce
1. Install the app from playstore.<br>
2. Launch the app and click on three horizontal lines on the top right corner of the app and select a category in potrait.<br> ![](https://s19.postimg.org/b7swvjgwj/20180406_135944.png)

3. Now change the orientation of the screen to landscape mode. Now you&apos;ll be shown all the apps irrespective of the category you selected in step 2. You can even check the catehory being changed by repeating step 2.<br>
App Version: 2.3.1 <br>
Device: Samsung Galaxy J5<br>
Operating system: Android 6.0.1

#### Recording Of The Bug
Here's the video recording of the bug.<br>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/RTpqQjAmrvw?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@neupanedipen/selected-category-changed-on-rotating-the-screen">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by MartinStyk** [comment]
Thanks for bringing this to my attention. I will look into it once the time allows. Thanks!

**Comment by MartinStyk** [comment]
This issue is now fixed. Release rolling out shortly
