### ISSUE TITLE
[Feature Request] Option to view AndroidManifest.xml of apk on SD card

### ISSUE THREAD

**Issue by shaobin0604** [MartinStyk/AndroidApkAnalyzer#30]
The **View AndroidManifest.xml** option only support apk that has been installed. 

Could you please add an option to support apks that has not been installed?

**Comment by MartinStyk** [comment]
Hi, technically i am not able to implement this feature. I haven't found a way to do it. :-(

**Comment by shaobin0604** [comment]
Hi, I've just find a way to implement this feature. 
Would you mind if I create a pull request?
