### ISSUE TITLE
Option to analyze apks on memory card 

### ISSUE THREAD

**Issue by Logmytech** [MartinStyk/AndroidApkAnalyzer#4]
I love your app but I want to analyze apks before sideloading them.  Please add a plus button in the bottom right to select an apk from memory. 

https://softwarerecs.stackexchange.com/questions/46260/android-application-for-analyzing-apks

**Comment by Logmytech** [comment]
I mean phone memory of external memory

**Comment by MartinStyk** [comment]
Hi @Logmytech, thank you for your feedback. 
Analysis of not installed APK files requires major changes in application logic. Analysis services rely on Android's PackageManager API which works only with installed packages.
I will take a look and try to find a solution for your proposal.

**Comment by Logmytech** [comment]
No wonder any other app had this feature.
I installed all apk analyzers only to be disappointed.

**Comment by MartinStyk** [comment]
This looks promising! I will work on this feature during the week and once ready, I will realease new version to Play Store

**Comment by MartinStyk** [comment]
This is implemented, I will proceed with testing
