### ISSUE TITLE
Info about source of installed app

### ISSUE THREAD

**Issue by Logmytech** [MartinStyk/AndroidApkAnalyzer#5]
Since you already get the signatures, this should be easy.

I hear that every apk is signed by the app store.

So info about wether the app is from Play store, Amazon Store or sideloaded(Unknown source).

There is already an app that has this feature called App detective.
It allows you to filter apps by source (Play Store, Amazon store, Sideloaded)
https://play.google.com/store/apps/details?id=com.zmarties.detective

![Sideloaded apps list](https://i.imgur.com/TdcAbJD.jpg)

**Comment by MartinStyk** [comment]
Sounds good, I will include it in next release

**Comment by Logmytech** [comment]
@MartinStyk If possible please add a filter for application source so that only apps of that sources are displayed.

Consider this case. I suspect there is a spyware like Cell bubble, Fspy on my phone.
I can filter to show sideloaded applications and see if any sideloaded app is requesting suspicious permissions.
Or I can see if some one installed a malicious sideloaded app while I don't sideload at all.
Checking each app for source is cumbersome.

I can always use App detective, but I'd like an Open Source app to be able to do that.

I think the problem with this is you need to rethink the GUI.

Please give me your thoughts on this.

**Comment by MartinStyk** [comment]
@Logmytech, it makes sense. 
When displaying app list, I try to load as few data as possible. I will take a look and add application source to enable filtering. 

According to scenario you mentioned, I will develop new feature which will detect potentially repackaged APK file.  Please, see #7

**Comment by MartinStyk** [comment]
Filtering is implemented. If you have any additional thoughts in this one, feel free to reopen this issue
