### ISSUE TITLE
Build failed. Keystore properties not found

### ISSUE THREAD

**Issue by Logmytech** [MartinStyk/AndroidApkAnalyzer#6]
I want to compile this app and I get the error `Error:(8, 0) C:\Users\MyUserName\StudioProjects\AndroidApkAnalyzer-master\keystore.properties (The system cannot find the file specified) <a href="openFile:C:\Users\Naruto\StudioProjects\AndroidApkAnalyzer-master\app\build.gradle">Open File</a>`

Google doesn't help for some reason.

Thanks!

**Comment by MartinStyk** [comment]
This was caused by gradle configuration for automatic package signing. 
Should be ok now, please try again
