### ISSUE TITLE
APK sideload install intent

### ISSUE THREAD

**Issue by Logmytech** [MartinStyk/AndroidApkAnalyzer#8]
It'd be nice if this app had a intent receiver that gives the user a chance to use this app when he/she clicks the apk to install it.
Since the app already has the option to select apk and analyze it.

Kinda like how some anti viruses like Malwarebytes give the option to scan an apk and install it after scan after clicking on the apk.

**Comment by MartinStyk** [comment]
I have been thinking about this feature and I will try to include it next release

**Comment by MartinStyk** [comment]
Feature is implemented in recent commits.

**Comment by MartinStyk** [comment]
This is already released.I close this issue
