### ISSUE TITLE
VirusTotal scan implementation

### ISSUE THREAD

**Issue by Logmytech** [MartinStyk/AndroidApkAnalyzer#9]
Maybe you can implement VirusTotal scanning feature.

If you don't want to deal with API keys etc. you can give an option to enter Virustotal API key with link and instructions to signup page.
The user can then go and create an API key on the Virustotal website and copy paste it.

**Comment by MartinStyk** [comment]
Hi, 
this feature is currently not on my radar.
In next few months I will focus on my own algorithm for detecting repackaged APKs
